spring:
  application:
    name: Routine-Pusher

  datasource:
    url: jdbc:postgresql://localhost:5432/routine-pusher
    username: postgres
    password: PgreWsl
    hikari:
      pool-size: 30
    driver-class-name: org.postgresql.Driver
    quartz:
      job-store-type: jdbc
      properties:
        org.quartz.threadPool:
          threadCount: 5

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: lembrete_queue
  exchange:
    name: lembrete_exchange
  routing:
    key: lembrete_key
