openapi: 3.0.1
info:
  title: Minha API
  description: Documentação da API carregada via YAML
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local

paths:
  /api/hello:
    get:
      summary: Retorna uma mensagem de boas-vindas
      description: Exemplo de endpoint carregado a partir de um arquivo YAML
      responses:
        "200":
          description: Resposta bem-sucedida
          content:
            application/json:
              schema:
                type: string
                example: "Olá, Swagger OpenAPI YAML!"