-- Schema inicial do Routine Pusher.
--
-- Espelha o que o Hibernate vinha gerando com ddl-auto: create-drop. A partir daqui o schema é
-- versionado e o Hibernate roda em 'validate': ele confere que o mapeamento bate com o banco no
-- boot, em vez de alterar o banco por conta própria.
--
-- Sobre as duas chaves de 'lembrete':
--   id   BIGINT — chave interna. Sequencial de propósito: mantém localidade no índice B-tree e
--                 deixa as FKs em 8 bytes. Nunca sai da camada de persistência.
--   uuid UUID   — chave de negócio. É por ela que a aplicação procura o lembrete, é ela que a API
--                 expõe e é ela que identifica o job no Quartz. Gerada no domínio, antes do INSERT.
--
-- Categoria tem só a chave sequencial: é dado de apoio, não trafega como identidade pública.

CREATE TABLE categoria (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome        VARCHAR(255) NOT NULL,
    cor         VARCHAR(255) NOT NULL UNIQUE,
    fator_ordem INTEGER      NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE lembrete (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid         UUID         NOT NULL UNIQUE,
    categoria_id BIGINT       NOT NULL,
    data_criacao TIMESTAMP(6) NOT NULL,
    titulo       VARCHAR(255) NOT NULL,
    descricao    VARCHAR(255),
    status       VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_lembrete_categoria FOREIGN KEY (categoria_id) REFERENCES categoria
);

CREATE TABLE notificacao (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lembrete_id      BIGINT UNIQUE,
    horario          TIME(6),
    proxima_execucao TIMESTAMP(6),
    ultima_execucao  TIMESTAMP(6),
    dt_inicio        TIMESTAMP(6),
    dt_fim           TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_notificacao_lembrete FOREIGN KEY (lembrete_id) REFERENCES lembrete
);

CREATE TABLE notificacao_metodo (
    notificacao_id BIGINT  NOT NULL,
    ordem          INTEGER NOT NULL,
    metodo         VARCHAR(255),
    PRIMARY KEY (ordem, notificacao_id),
    CONSTRAINT fk_notificacao_metodo FOREIGN KEY (notificacao_id) REFERENCES notificacao
);

CREATE TABLE notificacao_datas (
    notificacao_id  BIGINT  NOT NULL,
    ordem           INTEGER NOT NULL,
    dt_especificada TIMESTAMP(6),
    PRIMARY KEY (ordem, notificacao_id),
    CONSTRAINT fk_notificacao_datas FOREIGN KEY (notificacao_id) REFERENCES notificacao
);

CREATE TABLE recorrencia (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lembrete_id       BIGINT UNIQUE,
    quantidade        INTEGER,
    intervalo_dias    INTEGER,
    intervalo_horas   INTEGER,
    intervalo_minutos INTEGER,
    pos_semana        INTEGER,
    politica_dia_util VARCHAR(255) CHECK (politica_dia_util IN ('IGNORAR', 'PULAR', 'ADIAR', 'ANTECIPAR')),
    PRIMARY KEY (id),
    CONSTRAINT fk_recorrencia_lembrete FOREIGN KEY (lembrete_id) REFERENCES lembrete
);

CREATE TABLE recorrencia_dias_fixos (
    recorrencia_id BIGINT  NOT NULL,
    ordem          INTEGER NOT NULL,
    dia_fixo       INTEGER,
    PRIMARY KEY (ordem, recorrencia_id),
    CONSTRAINT fk_recorrencia_dias_fixos FOREIGN KEY (recorrencia_id) REFERENCES recorrencia
);

CREATE TABLE recorrencia_dias_semana (
    recorrencia_id BIGINT  NOT NULL,
    ordem          INTEGER NOT NULL,
    dia_semana     VARCHAR(255) CHECK (dia_semana IN ('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO')),
    PRIMARY KEY (ordem, recorrencia_id),
    CONSTRAINT fk_recorrencia_dias_semana FOREIGN KEY (recorrencia_id) REFERENCES recorrencia
);

-- A busca por uuid é o caminho de leitura de todo endpoint que recebe um identificador; o UNIQUE
-- acima já cria o índice que ela usa.
CREATE INDEX idx_lembrete_categoria ON lembrete (categoria_id);
