-- Sessão anônima: o "usuário" do demo. Ninguém cadastra login para testar um site que veio de um
-- post — a identidade nasce no primeiro request, vive num cookie e morre por inatividade.
--
-- Mesmo padrão de dupla chave do lembrete:
--   id   BIGINT — chave interna, sequencial, nunca sai da persistência.
--   uuid UUID   — o valor que viaja no cookie e escopa tudo que o visitante cria.
--
-- ultimo_acesso é o relógio da expiração: a faxina remove sessões parada há mais que a janela de
-- inatividade, junto com seus lembretes e agendamentos.

CREATE TABLE sessao_anonima (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid          UUID         NOT NULL UNIQUE,
    data_criacao  TIMESTAMP(6) NOT NULL,
    ultimo_acesso TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

-- Todo lembrete pertence a uma sessão. NOT NULL de saída: a tabela está vazia (nada foi a produção)
-- e lembrete sem dono é exatamente o que o modelo quer proibir.
ALTER TABLE lembrete
    ADD COLUMN sessao_id BIGINT NOT NULL,
    ADD CONSTRAINT fk_lembrete_sessao FOREIGN KEY (sessao_id) REFERENCES sessao_anonima;

-- Os dois caminhos de leitura quentes: "os lembretes desta sessão" (toda listagem) e
-- "sessões paradas antes do corte" (a faxina).
CREATE INDEX idx_lembrete_sessao ON lembrete (sessao_id);
CREATE INDEX idx_sessao_ultimo_acesso ON sessao_anonima (ultimo_acesso);
